spring:
  batch:
    jdbc:
      initialize-schema: always
    job:
      name: testjob
      enabled: false # 프로젝트 실행 시 자동으로 배치 작업이 가동되는 것을 방지
  datasource:
    url: "jdbc:mysql://localhost:3307/crops?serverTimezone=Asia/Seoul&characterEncoding=UTF-8"
    username: root
    password: "!123456"
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
management:
  endpoints:
    web:
      exposure:
        include: prometheus, health, info

  metrics:
    export:
      prometheus:
        enabled: true